### ISSUE TITLE
Bootstrap mixin most likely doesn't/shouldn't need to wrap display mixin

### ISSUE THREAD

**Issue by timgit** [ThirdCornerLLC/tc-grid#10]
Bootstrap should only be a style mixin

**Comment by Zacharias3690** [comment]
do we want to remove the requirement for tcDisplay in custom classes? It gives us some power when it comes to mobile designs, and technically the display is part of the class.

**Comment by timgit** [comment]
My original idea was that display should be common across all custom styles and implemented globally.  Just opened the less again and I see a media query that's not wrapped in the mixin, so it's kind of in a weird state.  We could leave it as a mixin if we want, but it would work equally well if we just inlined all the code directly in the .tcGrid__scope block.
