### ISSUE TITLE
Need a way to override button and sort icon styles

### ISSUE THREAD

**Issue by timgit** [ThirdCornerLLC/tc-grid#11]

**Comment by Zacharias3690** [comment]
Not sure about how to do this through a mixin, but the sort classes don't need a high specificity to change out the content. 
.tc-style_sort  {
    content: whatever
    font-family: whatever
}

took care of it.

**Comment by timgit** [comment]
I wouldn't want to force peeps into building the LESS. Perhaps we can just allow a class attribute like tc-row-class?  tc-sort-class?

**Comment by Zacharias3690** [comment]
You don't have to build the less for that to work. tc-style_sort has a low specificity, so you can overwrite it in your css files with the compiled less files.

**Comment by Zacharias3690** [comment]
Fixed with release 0.7.11
