### ISSUE TITLE
Prototype images instead of unicode for sort and page icons

### ISSUE THREAD

**Issue by timgit** [ThirdCornerLLC/tc-grid#14]
http://jsfiddle.net/9duk2ubf/ is an example

**Comment by Zacharias3690** [comment]
Not sure how I feel about this. I like being able to go in and change the content and font to change the icons. I do feel like we need a demo showing just how customizable the grid is though. Our demo now is pretty ugly.

**Comment by Zacharias3690** [comment]
Closing as we can override .tc-style_sort.desc/.asc:after pseudo element to replace the sort icon with whatever we want.
