### ISSUE TITLE
When paging, if you page beyond you get a "no result" page

### ISSUE THREAD

**Issue by goofygrin** [ThirdCornerLLC/tc-grid#31]
Something we came across with pagination..   Kyle mentioned its a TC Grid thing..

If you have 3 pages and you get to page 3 and click next you will get another blank page with a message saying no results...

**Comment by goofygrin** [comment]
The correct solution is that the pager should not give a next if there is not another page/you're at the last page.

**Comment by kylelynch** [comment]
Looked into it - it was just an implementation issue. We were keeping track of page count too simply (# of items / page size). Making sure page count rounds to ceiling fixes the issue, as the "next" button is set to gray out when current page == page count.

**Comment by timgit** [comment]
Did you try using options.paging.totalItemCount?  This is what the grid uses to calculate the page count
