### ISSUE TITLE
Need to specify which minimum of IE we're going to support.

### ISSUE THREAD

**Issue by timgit** [ThirdCornerLLC/tc-grid#32]
Based on our current API usage, it's at least IE9.

**Comment by Zacharias3690** [comment]
I think we should be able to just follow angular's support. We're not using much browser specific js

**Comment by timgit** [comment]
You mean now that you updated the bower dependency to Angular 1.3 and higher, right? :)

**Comment by Zacharias3690** [comment]
exactly. I needed 1.3 for controllerAs so we didn't have any more weird scope issues.

our original scoping made it so if we made a function in the controller called vm.first() when we called first in tc-grid it would call both tc-grid's first and the controller's first function.

**Comment by Zacharias3690** [comment]
Deciding on IE9 and up. AngularJS is keeping support for IE9 up through 1.5, and we're not using any other browser specific things.
