### ISSUE TITLE
Need a way to update data without double calling paging and sorting

### ISSUE THREAD

**Issue by Zacharias3690** [ThirdCornerLLC/tc-grid#33]
Currently when the table loads it calls onPageChange() and onSortChange(). If both of these exist, we end up double calling an endpoint.

To fix this we could add another option called update that takes a function which returns page, count, sort and is called in place of onPageChange and onSortChange

**Comment by timgit** [comment]
It doesn't call both:

```
                        if (vm.options.sorting.onSortChange)
                            sortChanged();
                        else if (vm.options.paging.onPageChange)
                            pageChanged();
```

**Comment by Zacharias3690** [comment]
You're right, double call was from an implementation issue
