### ISSUE TITLE
Unable to see table body data

### ISSUE THREAD

**Issue by bpowell415** [ThirdCornerLLC/tc-grid#37]
Using version0.7.10, the table doesn't display the cell data. I see the no-repeat iterate over my array, I confirm the data exists and has the right property.

**Comment by Zacharias3690** [comment]
Should be fixed as of 0.7.11

**Comment by bpowell415** [comment]
There are 2 different versions out now. I grabbed it from thirdcorenr llc
repo which is broken.

It is setting the row template html to "".

In your personal repo, it isn't the same code for the directive.

**Comment by Zacharias3690** [comment]
Looks like it's broken without a columnDisplay option. I'm fixing it now but a temp fix is setting options.columnDisplay to [1,2,...] to match the column index. so a table with 3 columns would be [1,2,3]

**Comment by Zacharias3690** [comment]
Resolved with 0.7.12
