### ISSUE TITLE
bower.json should list Bootstrap dependency

### ISSUE THREAD

**Issue by mbreedlove** [ThirdCornerLLC/tc-grid#4]
Readme shows tc-grid depends on Bootstrap, yet it does not appear in the bower.json dependencies.

**Comment by timgit** [comment]
I vote to kill the Bootstrap dependency (#1)

**Comment by mbreedlove** [comment]
Resolved in [4ef6991](https://github.com/ThirdCornerLLC/tc-grid/commit/4ef69914de3dad55a3a75a65fbd8872524de4b3a).

**Comment by mbreedlove** [comment]
@timgit,

Getting to that, it should be pretty simple. I just wanted to get this resolved to make development on my end easier.
