### ISSUE TITLE
Adding tc-row-link attribute to allow for rows to be clickable links

### ISSUE THREAD

**Issue by Zacharias3690** [ThirdCornerLLC/tc-grid#41]
biggest plus for this is getting the "right click and open in new tab" option instead of using javascript to load the next page. We can change the rows in the table to be anchors and style them like table rows similar to what we're doing with divs and simply append an href to it. What are y'alls thoughts this?

**Comment by goofygrin** [comment]
This is a must have regardless of how it's implemented.

**Comment by Zacharias3690** [comment]
PR #42 to fix this.
